language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1

install:
  - cd example
  - pip install -r requirements/dependency_base.txt
  - pip install -r requirements/base.txt
  - pip install -q Django==$DJANGO_VERSION

# command to run tests
script:
   coverage run --omit */site-packages/*,*/migrations/*,*/lib/* manage.py test issue_tracker.tests --settings=dj.settings.settings -v 2
